"""Index Document Generator — auto-generate navigation/index documents.

Supports three styles:
- flat:          Simple list for small repos (<20 docs)
- hierarchical:  Nested by directory structure
- categorical:   Grouped by status/type
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from lib.registry import DocRegistry
from lib.traceback import (
    DocMeta,
    compute_source_hash,
    format_frontmatter,
    get_head_commit,
    now_iso,
)


def generate_index(
    repo_root: Path,
    style: str = "auto",
    registry: DocRegistry | None = None,
) -> str:
    """Generate an index document for the repository.

    Args:
        repo_root: Repository root path.
        style: "auto", "flat", "hierarchical", or "categorical".
        registry: Pre-loaded registry (scans if None).

    Returns:
        Complete markdown content with traceback frontmatter.
    """
    if registry is None:
        registry = DocRegistry.load(repo_root)
        if registry is None:
            registry = DocRegistry.scan(repo_root)

    docs = registry.all_docs()

    if style == "auto":
        n = len(docs)
        style = "flat" if n < 20 else "hierarchical" if n < 100 else "categorical"

    generators = {
        "flat": _gen_flat,
        "hierarchical": _gen_hierarchical,
        "categorical": _gen_categorical,
    }
    gen = generators.get(style, _gen_flat)

    body = gen(docs, repo_root)

    # Build traceback frontmatter
    meta = {
        "doc_id": "_index",
        "source_paths": ["."],
        "source_tree_hash": compute_source_hash(repo_root, ["."]),
        "last_sync_commit": get_head_commit(repo_root),
        "sync_timestamp": now_iso(),
        "doc_version": 1,
        "status": "synced",
    }

    return format_frontmatter(meta) + "\n" + body


# ─── Generators ───────────────────────────────────────────────────────

_STATUS_ICONS = {
    "synced": "✅",
    "stale": "⚠️",
    "needs_review": "🔍",
    "draft": "📝",
    "source_missing": "❌",
}


def _gen_flat(docs: list[DocMeta], repo_root: Path) -> str:
    """Simple flat list of all documents."""
    now = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# 📚 Repository Documentation Index",
        "",
        f"> Auto-generated by repo-doc-engine | {now}",
        "",
        f"**Total documents**: {len(docs)}",
        "",
    ]

    if not docs:
        lines.append("_No traceable documents found. Run `scan` to discover documents._")
        return "\n".join(lines)

    lines.append("| Doc ID | Status | Sources | Last Sync |")
    lines.append("|:-------|:-------|:--------|:----------|")

    for doc in docs:
        icon = _STATUS_ICONS.get(doc.status, "·")
        sources = ", ".join(doc.source_paths[:3])
        if len(doc.source_paths) > 3:
            sources += f" (+{len(doc.source_paths) - 3})"
        ts = doc.sync_timestamp[:16] if doc.sync_timestamp else "—"
        rel_path = _relative_md_link(doc.filepath, repo_root) if doc.filepath else doc.doc_id
        lines.append(f"| {icon} [{doc.doc_id}]({rel_path}) | {doc.status} | {sources} | {ts} |")

    return "\n".join(lines)


def _gen_hierarchical(docs: list[DocMeta], repo_root: Path) -> str:
    """Nested by directory structure."""
    now = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M")

    # Group by first directory component
    groups: dict[str, list[DocMeta]] = {}
    for doc in docs:
        parts = doc.doc_id.split("/")
        group = parts[0] if len(parts) > 1 else "_root"
        groups.setdefault(group, []).append(doc)

    lines = [
        "# 📚 Repository Documentation Index",
        "",
        f"> Auto-generated by repo-doc-engine | {now}",
        "",
    ]

    # Summary
    total = len(docs)
    synced = sum(1 for d in docs if d.status == "synced")
    lines.append(f"**{total} documents** | {synced} synced ({round(synced/total*100) if total else 0}%)")
    lines.append("")

    for group_name in sorted(groups.keys()):
        group_docs = groups[group_name]
        if group_name == "_root":
            lines.append("## Root")
        else:
            lines.append(f"## {group_name}/")
        lines.append("")

        for doc in sorted(group_docs, key=lambda d: d.doc_id):
            icon = _STATUS_ICONS.get(doc.status, "·")
            name = doc.doc_id.split("/")[-1] if "/" in doc.doc_id else doc.doc_id
            rel_path = _relative_md_link(doc.filepath, repo_root) if doc.filepath else doc.doc_id
            lines.append(f"- {icon} [{name}]({rel_path}) — {doc.status}")

        lines.append("")

    return "\n".join(lines)


def _gen_categorical(docs: list[DocMeta], repo_root: Path) -> str:
    """Grouped by status category."""
    now = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M")

    lines = [
        "# 📚 Repository Documentation Index",
        "",
        f"> Auto-generated by repo-doc-engine | {now}",
        "",
    ]

    # Summary table
    total = len(docs)
    status_counts: dict[str, int] = {}
    for doc in docs:
        status_counts[doc.status] = status_counts.get(doc.status, 0) + 1

    lines.append("## Health Summary")
    lines.append("")
    lines.append("| Status | Count | Percentage |")
    lines.append("|:-------|:------|:-----------|")
    for status in ["synced", "stale", "needs_review", "draft", "source_missing"]:
        count = status_counts.get(status, 0)
        if count > 0:
            icon = _STATUS_ICONS.get(status, "·")
            pct = round(count / total * 100, 1) if total else 0
            lines.append(f"| {icon} {status} | {count} | {pct}% |")
    lines.append("")

    # Group by status
    categories = [
        ("⚠️ Needs Attention", ["stale", "needs_review", "source_missing"]),
        ("📝 Drafts", ["draft"]),
        ("✅ Synced", ["synced"]),
    ]

    for title, statuses in categories:
        cat_docs = [d for d in docs if d.status in statuses]
        if not cat_docs:
            continue

        lines.append(f"## {title}")
        lines.append("")
        for doc in sorted(cat_docs, key=lambda d: d.doc_id):
            icon = _STATUS_ICONS.get(doc.status, "·")
            rel_path = _relative_md_link(doc.filepath, repo_root) if doc.filepath else doc.doc_id
            sources = ", ".join(doc.source_paths[:2])
            lines.append(f"- {icon} [{doc.doc_id}]({rel_path}) ← {sources}")
        lines.append("")

    return "\n".join(lines)


# ─── Helpers ──────────────────────────────────────────────────────────

def _relative_md_link(filepath: str, repo_root: Path) -> str:
    """Convert absolute filepath to relative markdown link."""
    try:
        rel = Path(filepath).relative_to(repo_root)
        return str(rel)
    except (ValueError, TypeError):
        return filepath
